### ISSUE TITLE
Document deployed contract addresses

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/blobstream-contracts#183]
## Problem

It isn't clear where the QGB contract defined in this repo is deployed. I couldn't find this info in the README.md or https://docs.celestia.org/category/qgb/

## Proposal

In the README.md, add a table that describes where the QGB smart contract is deployed. Potential columns for the table: network chain ID, contract address w/ link, commit hash in this repo that was deployed

**Comment by SweeXordious** [comment]
I dont think there is any officially deployed contract from our side. We're just deploying them for tests.

But would be good when we start deploying the QGB.

**Comment by SweeXordious** [comment]
I dont think there is any officially deployed contract from our side. We're just deploying them for tests.

But would be good when we start deploying the QGB.

**Comment by rootulp** [comment]
We don't actually use the .sol contract in this repo. Instead, contracts from https://github.com/succinctlabs/blobstreamx are used. See https://docs.celestia.org/developers/blobstream#deployed-contracts
