### ISSUE TITLE
Make DAVerifier functions external instead of public

### ISSUE THREAD

**Issue by adlerjohn** [celestiaorg/blobstream-contracts#237]
`verifyRowRootToDataRootTupleRoot` and `verifyMultiRowRootsToDataRootTupleRoot` are `public`, when they can be `external`.

**Comment by SweeXordious** [comment]
I think internal makes more sense since rollups will be using their contracts for verification instead of calling external ones. So it makes sense to make them internal

**Comment by Ferret-san** [comment]
From talking to rollup teams, they generally prefer internal libraries when there's contract space for it. And usually there's space for it in the contracts where the libraries would be used.
