### ISSUE TITLE
README: add links to audits

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/blobstream-contracts#250]
## Context

Informal Systems audited these contracts

## Proposal

Upload the audit report PDF. Add a link in the README.

**Comment by adlerjohn** [comment]
Do we want binary files checked in to version control? Can they not be uploaded to e.g. the Wiki of this repo instead?

**Comment by rootulp** [comment]
Good point, wiki seems fine to me. It looks like 3 audit reports were already uploaded to the wiki at https://github.com/celestiaorg/blobstream-contracts/wiki. They just haven't been linked from the README
