### ISSUE TITLE
Investigate switching from a custom prover to SP1 for BlobstreamX

### ISSUE THREAD

**Issue by rach-id** [celestiaorg/blobstream-contracts#315]
We should investigate the transition from the current BlobstreamX prover to using SP1. This investigation should include:

- How easy it is to switch
- If the existing tooling is sufficient
- If the generated proof will require to be wrapped.
- Is the EVM verifier the same or different

**Comment by evan-forbes** [comment]
my understanding of this is that we are are pursuing the sp1 refactor, and audits can be scheduled after all of the changes for the bitmap are added. 

Is this the case? if yes, can we close this issue, if no, can we add further context here around what information is missing to make a decision?
