### ISSUE TITLE
Write ADR for dynamic data commitment block ranges

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/blobstream-contracts#54]
The QGB relies on validators signing commitments to erasure block data over a range of blocks. For the MVP, we are using an identical block range for each `DataCommitment`.  This range of blocks will likely need to be significantly more dynamic to accommodate different rollups.  

- How can we do this in an efficient way? 
- Does it matter if ranges overlap? 
- How will this affect slashing? 
- Will the rollup batch producers need to ask the celestia validators to sign commitments over custom ranges? If so, what should that look like?
- Do any changes need to be made to the contracts?

**Comment by rach-id** [comment]
No longer relevant because we have BlobstreamX supporting
